[[rulesets]]
group = "ğŸŒ€ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list"

[[rulesets]]
group = "ğŸŒ€ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list"

[[rulesets]]
group = "ğŸ“› ç¦æ­¢é€šè¡Œ"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.list"

[[rulesets]]
group = "ğŸŒ‘ AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"

[[rulesets]]
group = "ğŸŒ‘ AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list"

[[rulesets]]
group = "ğŸŒ‘ AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list"

[[rulesets]]
group = "ğŸŒ‘ AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list"

[[rulesets]]
group = "ğŸŒ‘ AI"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list"

[[rulesets]]
group = "ğŸ–¥ Developer"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Developer/Developer.list"

[[rulesets]]
group = "ğŸ–¥ Developer"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list"

[[rulesets]]
group = "ğŸ–¥ Developer"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Jetbrains/Jetbrains.list"

[[rulesets]]
group = "ğŸ’¬ Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ‡¬ GoogleFCM"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list"

[[rulesets]]
group = "ğŸªŸ Microsoft"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list"

[[rulesets]]
group = "ğŸ¥ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list"

[[rulesets]]
group = "ğŸ¥ å›½å†…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list"

[[rulesets]]
group = "ğŸª€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list"

[[rulesets]]
group = "ğŸŒ€ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaNoMedia/ChinaNoMedia.list"

[[rulesets]]
group = "ğŸŒ€ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
