[[custom_groups]]
name = "🪀 节点选择"
type = "select"
rule = [
	"[]💤 自动选择",
	"[]🖐 手动选择",
	"[]🔮 负载均衡",
	"[]⚙️ 故障转移",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "💤 自动选择"
type = "url-test"
rule = [
	"(^(?!.*(((?<![^\\s\\-_\\(])Home(?![^\\s\\-_\\)]))|(\\(?((x|X)?(\\d+)(\\.?\\d+)?)(x|X)\\)?))).*)",
]
url = "https://www.gstatic.com/generate_204"
interval = 3600

[[custom_groups]]
name = "🖐 手动选择"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "🏠 家宽节点"
type = "select"
rule = ["(?<![^\\s\\-_\\(])Home(?![^\\s\\-_\\)])"]

[[custom_groups]]
name = "🌠 倍率节点"
type = "select"
rule = ["\\(?((x|X)?(\\d+)(\\.?\\d+)?)(x|X)\\)?"]

[[custom_groups]]
name = "🌑 AI"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🖥 Developer"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "💬 Telegram"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🇬 GoogleFCM"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🇬 Google"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🪟 OneDrive"
type = "select"
rule = [
	"[]🌀 全球直连",
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🪟 Microsoft"
type = "select"
rule = [
	"[]🌀 全球直连",
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🎮 Game"
type = "select"
rule = [
	"[]🌀 全球直连",
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🎥 国内媒体"
type = "select"
rule = [
	"[]🌀 全球直连",
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🎥 国外媒体"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "📛 禁止通行"
type = "select"
rule = ["[]REJECT", "[]🌀 全球直连"]

[[custom_groups]]
name = "🇭🇰 香港节点"
type = "select"
rule = [
	"(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|香港)",
]

[[custom_groups]]
name = "🇹🇼 台湾节点"
type = "select"
rule = ["(?i:\\bTW[N]?\\b|Taiwan|新北|彰化|\\bCHT\\b|\\bHINET\\b|台湾)"]

[[custom_groups]]
name = "🇸🇬 狮城节点"
type = "select"
rule = ["(?i:\\bSG[P]?\\b|Singapore|新加坡|狮城)"]

[[custom_groups]]
name = "🇺🇸 美国节点"
type = "select"
rule = ["(?i:\\bUS[A]?\\b|America|United.*?States|LA|Los|H(?:awai)?i)"]

[[custom_groups]]
name = "🇬🇧 英国节点"
type = "select"
rule = ["(?i:\\bUK\\b|\\bGB[R]?\\b|England|United.*?Kingdom|London|英国|伦敦)"]

[[custom_groups]]
name = "🇰🇷 韩国节点"
type = "select"
rule = ["(?i:\\bK[O]?R\\b|Korea|首尔|韩|韓|韩国)"]

[[custom_groups]]
name = "🇯🇵 日本节点"
type = "select"
rule = ["(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉)"]

[[custom_groups]]
name = "🏳️‍⚧️ 冷门节点"
type = "select"
rule = ["(^(?!.*(🇭🇰|🇹🇼|🇸🇬|🇺🇸|🇬🇧|🇰🇷|🇯🇵)).*)"]

[[custom_groups]]
name = "🌀 全球直连"
type = "select"
rule = [
	"[]DIRECT",
	"(?i:\\bC[H]?N\\b|China|Back|回国|Beijing|Shanghai|Guangzhou|Shenzhen|Hangzhou|Changzhou|Xuzhou|Qingdao|Ningbo|Zhenjiang|Chengdu|Hebei|Shanxi|Liaoning|Jilin|Heilongjiang|Jiangsu|Zhejiang|Anhui|Fujian|Jiangxi|Shandong|Henan|Hubei|Hunan|Guangdong|Hainan|Sichuan|Guizhou|Yunnan|Shaanxi|Gansu|Qinghai|Neimenggu|Guangxi|Xizang|Ningxia|Xinjiang|中国|北京|上海|广州|深圳|杭州|常州|徐州|青岛|宁波|镇江|成都|河北|山西|辽宁|吉林|黑龙江|江苏|浙江|安徽|福建|江西|山东|河南|湖北|湖南|广东|海南|四川|贵州|云南|陕西|甘肃|青海|内蒙古|广西|西藏|宁夏|新疆)",
]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = [
	"[]🪀 节点选择",
	"[]🖐 手动选择",
	"[]🏠 家宽节点",
	"[]🌠 倍率节点",
	"[]🌀 全球直连",
	"[]🇭🇰 香港节点",
	"[]🇹🇼 台湾节点",
	"[]🇸🇬 狮城节点",
	"[]🇺🇸 美国节点",
	"[]🇬🇧 英国节点",
	"[]🇰🇷 韩国节点",
	"[]🇯🇵 日本节点",
	"[]🏳️‍⚧️ 冷门节点",
]

[[custom_groups]]
name = "🔮 负载均衡"
type = "load-balance"
rule = [".*"]
url = "https://www.gstatic.com/generate_204"
interval = 3600
strategy = "consistent-hashing"

[[custom_groups]]
name = "⚙️ 故障转移"
type = "fallback"
rule = [".*"]
url = "https://www.gstatic.com/generate_204"
interval = 3600
